import sys
import time
print("Welcome to the DATAPWNR. Specializing in downloading and uploading wirelessly, no fuss! Enjoy your stay.")
time.sleep(4)
print("██████╗  █████╗ ████████╗ █████╗ ██████╗ ██╗    ██╗███╗   ██╗██████╗")
print("██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗██║    ██║████╗  ██║██╔══██╗")
print("██║  ██║███████║   ██║   ███████║██████╔╝██║ █╗ ██║██╔██╗ ██║██████╔╝")
print("██║  ██║██╔══██║   ██║   ██╔══██║██╔═══╝ ██║███╗██║██║╚██╗██║██╔══██╗")
print("██████╔╝██║  ██║   ██║   ██║  ██║██║     ╚███╔███╔╝██║ ╚████║██║  ██║")
print("╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝      ╚══╝╚══╝ ╚═╝  ╚═══╝╚═╝  ╚═╝")
time.sleep(2)
print("Data Initialization Started...")
question = input('Execute?: ')
if question == 'y' or 'Y':
      time.sleep(2)
      print("Initialization Complete.")
      time.sleep(3)
      print("Downloading Data...")
      print("Downloading: |#--------------------")
      time.sleep(1)
      print("Downloading: |##-------------------")
      time.sleep(1)
      print("Downloading: |###------------------")
      time.sleep(1)
      print("Downloading: |####-----------------")
      time.sleep(1)
      print("Downloading: |#####----------------")
      time.sleep(1)
      print("Downloading: |######---------------")
      time.sleep(1)
      print("Downloading: |#######--------------")
      time.sleep(1)
      print("Downloading: |########-------------")
      time.sleep(1)
      print("Downloading: |#########------------")
      time.sleep(1)
      print("Downloading: |##########-----------")
      time.sleep(1)
      print("Downloading: |###########----------")
      time.sleep(1)
      print("Downloading: |############---------")
      time.sleep(1)
      print("Downloading: |#############--------")
      time.sleep(1)
      print("Downloading: |##############-------")
      time.sleep(1)
      print("Downloading: |###############------")
      time.sleep(1)
      print("Downloading: |################-----")
      time.sleep(1)
      print("Downloading: |#################----")
      time.sleep(1)
      print("Downloading: |##################---")
      time.sleep(1)
      print("Downloading: |###################--")
      time.sleep(1)
      print("Downloading: |####################-")
      time.sleep(1)
      print("Downloading: |#####################")
      time.sleep(3)
      print("Download Complete.")
      time.sleep(3)
      print("Uploading Data to Primary Server...")
      time.sleep(3)
      print("Uploading: |#--------------------")
      time.sleep(1)
      print("Uploading: |##-------------------")
      time.sleep(1)
      print("Uploading: |###------------------")
      time.sleep(1)
      print("Uploading: |####-----------------")
      time.sleep(1)
      print("Uploading: |#####----------------")
      time.sleep(1)
      print("Uploading: |######---------------")
      time.sleep(1)
      print("Uploading: |#######--------------")
      time.sleep(1)
      print("Uploading: |########-------------")
      time.sleep(1)
      print("Uploading: |#########------------")
      time.sleep(1)
      print("Uploading: |##########-----------")
      time.sleep(1)
      print("Uploading: |###########----------")
      time.sleep(1)
      print("Uploading: |############---------")
      time.sleep(1)
      print("Uploading: |#############--------")
      time.sleep(1)
      print("Uploading: |##############-------")
      time.sleep(1)
      print("Uploading: |###############------")
      time.sleep(1)
      print("Uploading: |################-----")
      time.sleep(1)
      print("Uploading: |#################----")
      time.sleep(1)
      print("Uploading: |##################---")
      time.sleep(1)
      print("Uploading: |###################--")
      time.sleep(1)
      print("Uploading: |####################-")
      time.sleep(1)
      print("Uploading: |#####################")
      time.sleep(1)
      print("Upload Complete")
