import sys
import time
print("Welcome to the DATAPWNR. Enjoy your stay.")
time.sleep(4)
print(" /$$$$$$$   /$$$$$$  /$$$$$$$$ /$$$$$$  /$$$$$$$  /$$      /$$ /$$   /$$ /$$$$$$$")
print("| $$__  $$ /$$__  $$|__  $$__//$$__  $$| $$__  $$| $$  /$ | $$| $$$ | $$| $$__  $$")
print("| $$  \ $$| $$  \ $$   | $$  | $$  \ $$| $$  \ $$| $$ /$$$| $$| $$$$| $$| $$  \ $$")
print("| $$  | $$| $$$$$$$$   | $$  | $$$$$$$$| $$$$$$$/| $$/$$ $$ $$| $$ $$ $$| $$$$$$$/")
print("| $$  | $$| $$__  $$   | $$  | $$__  $$| $$____/ | $$$$_  $$$$| $$  $$$$| $$__  $$")
print("| $$  | $$| $$  | $$   | $$  | $$  | $$| $$      | $$$/ \  $$$| $$\  $$$| $$  \ $$")
print("| $$$$$$$/| $$  | $$   | $$  | $$  | $$| $$      | $$/   \  $$| $$ \  $$| $$  | $$")
print("|_______/ |__/  |__/   |__/  |__/  |__/|__/      |__/     \__/|__/  \__/|__/  |__/")
time.sleep(2)
print("Data Initialization Started...")
question = input('Execute?: ')
if question == 'y' or 'Y':
      time.sleep(2)
      print("Initialization Complete.")
      time.sleep(3)
      print("Downloading Data...")
      print("Downloading: |#--------------------")
      time.sleep(2)
      print("Downloading: |##-------------------")
      time.sleep(2)
      print("Downloading: |###------------------")
      time.sleep(2)
      print("Downloading: |####-----------------")
      time.sleep(2)
      print("Downloading: |#####----------------")
      time.sleep(2)
      print("Downloading: |######---------------")
      time.sleep(2)
      print("Downloading: |#######--------------")
      time.sleep(2)
      print("Downloading: |########-------------")
      time.sleep(2)
      print("Downloading: |#########------------")
      time.sleep(2)
      print("Downloading: |##########-----------")
      time.sleep(2)
      print("Downloading: |###########----------")
      time.sleep(2)
      print("Downloading: |############---------")
      time.sleep(2)
      print("Downloading: |#############--------")
      time.sleep(2)
      print("Downloading: |##############-------")
      time.sleep(2)
      print("Downloading: |###############------")
      time.sleep(2)
      print("Downloading: |################-----")
      time.sleep(2)
      print("Downloading: |#################----")
      time.sleep(2)
      print("Downloading: |##################---")
      time.sleep(2)
      print("Downloading: |###################--")
      time.sleep(2)
      print("Downloading: |####################-")
      time.sleep(2)
      print("Downloading: |#####################")
      wait(3)
      print("Download Complete.")
      wait(3)
      print("Uploading Data to Primary Server...")
      wait(3)
      print("Uploading: |#--------------------")
      time.sleep(2)
      print("Uploading: |##-------------------")
      time.sleep(2)
      print("Uploading: |###------------------")
      time.sleep(2)
      print("Uploading: |####-----------------")
      time.sleep(2)
      print("Uploading: |#####----------------")
      time.sleep(2)
      print("Uploading: |######---------------")
      time.sleep(2)
      print("Uploading: |#######--------------")
      time.sleep(2)
      print("Uploading: |########-------------")
      time.sleep(2)
      print("Uploading: |#########------------")
      time.sleep(2)
      print("Uploading: |##########-----------")
      time.sleep(2)
      print("Uploading: |###########----------")
      time.sleep(2)
      print("Uploading: |############---------")
      time.sleep(2)
      print("Uploading: |#############--------")
      time.sleep(2)
      print("Uploading: |##############-------")
      time.sleep(2)
      print("Uploading: |###############------")
      time.sleep(2)
      print("Uploading: |################-----")
      time.sleep(2)
      print("Uploading: |#################----")
      time.sleep(2)
      print("Uploading: |##################---")
      time.sleep(2)
      print("Uploading: |###################--")
      time.sleep(2)
      print("Uploading: |####################-")
      time.sleep(2)
      print("Uploading: |#####################")
      time.sleep(2)
      print("Upload Complete")
      end
