print("Welcome to the DATAPWNR. Enjoy your stay.")
wait(4)
print(" /$$$$$$$   /$$$$$$  /$$$$$$$$ /$$$$$$  /$$$$$$$  /$$      /$$ /$$   /$$ /$$$$$$$")
wait(1)
print("| $$__  $$ /$$__  $$|__  $$__//$$__  $$| $$__  $$| $$  /$ | $$| $$$ | $$| $$__  $$")
wait(1)
print("| $$  \ $$| $$  \ $$   | $$  | $$  \ $$| $$  \ $$| $$ /$$$| $$| $$$$| $$| $$  \ $$")
wait(1)
print("| $$  | $$| $$$$$$$$   | $$  | $$$$$$$$| $$$$$$$/| $$/$$ $$ $$| $$ $$ $$| $$$$$$$/")
wait(1)
print("| $$  | $$| $$__  $$   | $$  | $$__  $$| $$____/ | $$$$_  $$$$| $$  $$$$| $$__  $$")
wait(1)
print("| $$  | $$| $$  | $$   | $$  | $$  | $$| $$      | $$$/ \  $$$| $$\  $$$| $$  \ $$")
wait(1)
print("| $$$$$$$/| $$  | $$   | $$  | $$  | $$| $$      | $$/   \  $$| $$ \  $$| $$  | $$")
wait(1)
print("|_______/ |__/  |__/   |__/  |__/  |__/|__/      |__/     \__/|__/  \__/|__/  |__/")
wait(2)
Print("Data Initialization Started...")
question = input('Execute?: ')
      if question == 'y' or 'Y':
      then
      wait(2)
      print("Initialization Complete.")
      wait(3)
      print("Downloading Data...")
      print("Downloading: |#--------------------")
      wait(2)
      print("Downloading: |##-------------------")
      wait(2)
      print("Downloading: |###------------------")
      wait(2)
      print("Downloading: |####-----------------")
      wait(2)
      print("Downloading: |#####----------------")
      wait(2)
      print("Downloading: |######---------------")
      wait(2)
      print("Downloading: |#######--------------")
      wait(2)
      print("Downloading: |########-------------")
      wait(2)
      print("Downloading: |#########------------")
      wait(2)
      print("Downloading: |##########-----------")
      wait(2)
      print("Downloading: |###########----------")
      wait(2)
      print("Downloading: |############---------")
      wait(2)
      print("Downloading: |#############--------")
      wait(2)
      print("Downloading: |##############-------")
      wait(2)
      print("Downloading: |###############------")
      wait(2)
      print("Downloading: |################-----")
      wait(2)
      print("Downloading: |#################----")
      wait(2)
      print("Downloading: |##################---")
      wait(2)
      print("Downloading: |###################--")
      wait(2)
      print("Downloading: |####################-")
      wait(2)
      print("Downloading: |#####################")
      wait(3)
      print("Download Complete.")
      wait(3)
      print("Uploading Data to Primary Server...")
      wait(3)
      print("Uploading: |#--------------------")
      wait(2)
      print("Uploading: |##-------------------")
      wait(2)
      print("Uploading: |###------------------")
      wait(2)
      print("Uploading: |####-----------------")
      wait(2)
      print("Uploading: |#####----------------")
      wait(2)
      print("Uploading: |######---------------")
      wait(2)
      print("Uploading: |#######--------------")
      wait(2)
      print("Uploading: |########-------------")
      wait(2)
      print("Uploading: |#########------------")
      wait(2)
      print("Uploading: |##########-----------")
      wait(2)
      print("Uploading: |###########----------")
      wait(2)
      print("Uploading: |############---------")
      wait(2)
      print("Uploading: |#############--------")
      wait(2)
      print("Uploading: |##############-------")
      wait(2)
      print("Uploading: |###############------")
      wait(2)
      print("Uploading: |################-----")
      wait(2)
      print("Uploading: |#################----")
      wait(2)
      print("Uploading: |##################---")
      wait(2)
      print("Uploading: |###################--")
      wait(2)
      print("Uploading: |####################-")
      wait(2)
      print("Uploading: |#####################")
      wait(3)
      print("Upload Complete")
      end
