#python
import os
import sys
import time
import random
#--------------
print("⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⢠⡆⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠈⣷⣄⠀⠀⠀⠀⣾⣷⠀⠀⠀⠀⣠⣾⠃⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⢿⠿⠃⠀⠀⠀⠉⠉⠁⠀⠀⠐⠿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣤⣶⣶⣶⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⢀⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⣠⣶⣿⣿⡿⣿⣿⣿⡿⠋⠉⠀⠀⠉⠙⢿⣿⣿⡿⣿⣿⣷⣦⡀⠀⠀⠀")
print("⠀⢀⣼⣿⣿⠟⠁⢠⣿⣿⠏⠀⠀⢠⣤⣤⡀⠀⠀⢻⣿⣿⡀⠙⢿⣿⣿⣦⠀⠀         All")
print("⣰⣿⣿⡟⠁⠀⠀⢸⣿⣿⠀⠀⠀⢿⣿⣿⡟⠀⠀⠈⣿⣿⡇⠀⠀⠙⣿⣿⣷⡄         Seeing")
print("⠈⠻⣿⣿⣦⣄⠀⠸⣿⣿⣆⠀⠀⠀⠉⠉⠀⠀⠀⣸⣿⣿⠃⢀⣤⣾⣿⣿⠟⠁         Eye.")
print("⠀⠀⠈⠻⣿⣿⣿⣶⣿⣿⣿⣦⣄⠀⠀⠀⢀⣠⣾⣿⣿⣿⣾⣿⣿⡿⠋⠁⠀⠀")
print("⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠁⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠛⠿⠿⠿⠿⠿⠿⠛⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⢰⣷⡦⠀⠀⠀⢀⣀⣀⠀⠀⠀⢴⣾⡇⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⣸⠟⠁⠀⠀⠀⠘⣿⡇⠀⠀⠀⠀⠙⢷⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠻⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀")
time.sleep(2)
print("██████╗ ██╗  ██╗ ██████╗  ██████╗ ███╗   ███╗ █████╗ ")
print("██╔══██╗██║  ██║██╔═══██╗██╔═══██╗████╗ ████║██╔══██╗")
print("██████╔╝███████║██║   ██║██║   ██║██╔████╔██║███████║")
print("██╔═══╝ ██╔══██║██║   ██║██║   ██║██║╚██╔╝██║██╔══██║")
print("██║     ██║  ██║╚██████╔╝╚██████╔╝██║ ╚═╝ ██║██║  ██║")
print("╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝")
time.sleep(2)
print("In Your System Since 2020.")
time.sleep("1")
print("Scanning Main Network for Open Port or Gateway...")
print("Scanning: |#--------------------")
time.sleep(0.5)
print("Scanning: |##-------------------")
time.sleep(0.5)
print("Scanning: |###------------------")
time.sleep(0.5)
print("Scanning: |####-----------------")
time.sleep(0.5)
print("Scanning: |#####----------------")
time.sleep(0.5)
print("Scanning: |######---------------")
time.sleep(0.5)
print("Scanning: |#######--------------")
time.sleep(0.5)
print("Scanning: |########-------------")
time.sleep(0.5)
print("Scanning: |#########------------")
time.sleep(0.5)
print("Scanning: |##########-----------")
time.sleep(0.5)
print("Scanning: |###########----------")
time.sleep(0.5)
print("Scanning: |############---------")
time.sleep(0.5)
print("Scanning: |#############--------")
time.sleep(0.5)
print("Scanning: |##############-------")
time.sleep(0.5)
print("Scanning: |###############------")
time.sleep(0.5)
print("Scanning: |################-----")
time.sleep(0.5)
print("Scanning: |#################----")
time.sleep(0.5)
print("Scanning: |##################---")
time.sleep(0.5)
print("Scanning: |###################--")
time.sleep(0.5)
print("Scanning: |####################-")
time.sleep(0.5)
print("Scanning: |#####################")
print("def main():")
time.sleep(0.6)      
print("	parser,args = PArguments.Main_Arguments()")
time.sleep(0.6)
print("      if args.target == False:")
time.sleep(0.6)
print("      if args.help == False:")
time.sleep(0.6)
print("     sys.exit(UsageMain())")
time.sleep(0.6) 
print("      else:")
time.sleep(0.6)
print("			sys.exit(parser.print_help())")
time.sleep(0.6)
print("      else:")
time.sleep(0.6)
print("      process = getProcess(args)")
time.sleep(0.6)
print("      if len(process()) == 0:")
time.sleep(0.6)
print("      if args.help == False:")
time.sleep(0.6)
print("      sys.exit(UsageMain())")
time.sleep(0.6)
print("      else:")
time.sleep(0.6)
print("      sys.exit(parser.print_help())")
time.sleep(0.6)
print("      else:")
time.sleep(0.6)
print("      for _ in process():")
time.sleep(0.6)
print("				Handle(_,args)")
time.sleep(0.6)

print("      if __name__ == '__main__':")
time.sleep(0.6)
print("      main()")
time.sleep(0.6)
print("      class Ping:")
time.sleep(0.6)
print("      def __init__(self,tgt,to):")
time.sleep(0.6)
print("      self.tgt = domain_resolver(tgt,True)")
time.sleep(0.6)
print("      self.to = to")
time.sleep(0.6)
print("      self.id = os.getpid() & 0xFFFF")
time.sleep(0.6)
print("      self.my_socket = create_icmp_socket(self.to)")
time.sleep(0.6)
print("      builder = PingHeader(self.tgt)")
time.sleep(0.6)
print("		self.pkt = builder.building_packet()")
time.sleep(0.6)
print("      def send(self):")
time.sleep(0.6)
print("      send_time = time.time()")
time.sleep(0.6)
print("      self.my_socket.sendto(self.pkt, (self.tgt, 1))")
time.sleep(0.6)
print("		return send_time")
time.sleep(0.6)
print("      def receive(self):")
time.sleep(0.6)
print("      while True:")
time.sleep(0.6)
print("      select_start = time.time()")
time.sleep(0.6)
print("     inputready, outputready, exceptready = select.select([self.my_socket], [], [], self.to)")
time.sleep(0.6) 
print("      select_duration = (time.time() - select_start)")
time.sleep(0.6)
print("      if inputready == []:")
time.sleep(0.6)
print("				return 0, 0, 0, None, None")
time.sleep(0.6)
print("			packet, address = self.my_socket.recvfrom(65536)")
time.sleep(0.6)
print("			receive_time = time.time()")
time.sleep(0.6)
print("      icmpHeader = packet[20:28]")
time.sleep(0.6)
print("      type, code, checksum, packetID, sequence = struct.unpack(bbHHh, icmpHeader)")
time.sleep(0.6)
print("      if packetID == self.id:")
time.sleep(0.6)
print("				return receive_time")
time.sleep(0.6)
print("			timeout = timeout - select_duration")
time.sleep(0.6)
print("      if timeout <= 0:")
time.sleep(0.6)
print("				return 0, 0, 0, None, None")
time.sleep(0.6)
print("	def _start_icmp(self):")
time.sleep(0.6)		
print("      for i in range(0,1):")
time.sleep(0.6)
print("      try:")
time.sleep(0.6)
print("      send_time = self.send()")
time.sleep(0.6)
print("      receive_time = self.receive()")
time.sleep(0.6)
print("      except:")
time.sleep(0.6)
print("				return None")
time.sleep(0.6)
print("		return (receive_time - send_time) * 10")
time.sleep(0.5)
print("Scan Complete")
print("Exploitable Open Port:")
time.sleep(1)
print(random.randint(45, 65535))
time.sleep(1)
question = input('Execute?: ')
if question == 'y' or 'Y'
print("class Server:")
time.sleep(0.3)
print("    def __init__(self, port):")
time.sleep(0.3)
print("        self.logger = logging.getLogger(LOGGER_ID)")
time.sleep(0.3)
print("        self.thread_accept = None")
time.sleep(0.3)
print("        self.port = port")
time.sleep(0.3)
print("        self.connections = []")
time.sleep(0.3)
print("        self.addresses = []")
time.sleep(0.3)
print("       self.encryption = Encryption()")
time.sleep(0.3) 
print("       self.fernet = self.encryption.fernet")
time.sleep(0.3)
print("       self.listener = socket.socket()")
time.sleep(0.3)
print("        try:")
time.sleep(0.3)
print("            self.listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR,")
time.sleep(0.3)
print("                                     1)")
time.sleep(0.3)
print("        except socket.error as e:")
time.sleep(0.3)
print("            self.logger.error(Error creating socket {e}")
time.sleep(0.3)
print("            sys.exit(0)")
time.sleep(0.3)
print("    def listen_asych(self):")
time.sleep(0.3)
print("        def bind():")
time.sleep(0.3)
print("            try:")
time.sleep(0.3)
print("                self.listener.bind(("0.0.0.0", self.port))")
time.sleep(0.3)
print("                self.listener.listen(20)")
time.sleep(0.3)
print("            except socket.error as e:")
time.sleep(0.3)
print("                self.logger.warning(Error binding socket {e}\nRetrying...)")
time.sleep(0.3)
print("                time.sleep(3)")
time.sleep(0.3)
print("                bind()")
time.sleep(0.3)
print("        bind()")
time.sleep(0.3)
print("        self.logger.info(fListening on port {self.port}")
time.sleep(0.3)
print("        def socket_accept():")
time.sleep(0.3)
print("            while True:")
time.sleep(0.3)
print("                try:")
time.sleep(0.3)
print("                    _socket, address = self.listener.accept()")
time.sleep(0.3)
print("                    _socket.setblocking(True)")
time.sleep(0.3)
print("                    es = EncryptedSocket(_socket, self.fernet)")
time.sleep(0.3)
                    
                    
print("                    es.send(base64.b64encode(self.encryption.key), False)")
time.sleep(0.3)
print("                    self.logger.debug(send key: {self.encryption.key}")
time.sleep(0.3)
print("                    while True:")
time.sleep(0.3)                        
print("                        response = es.recv_json()")
time.sleep(0.3)
print("                        if response[key] == CLIENT_HANDSHAKE:")
time.sleep(0.3)
print("                            break")
time.sleep(0.3)
print("                    address = {**{ip: address[0], port: address[1]}, **response = value], **{connected: True}}")
time.sleep(0.3)
print("                    if es.socket in self.connections:")
time.sleep(0.3)                                                                                                   
print("                        self.addresses[self.connections.index(es.socket)][connected] = True")
time.sleep(0.3)                                                                                                   
print("                    else:")
time.sleep(0.3)                                                                                                   
print("                        self.connections.append(es.socket)")
time.sleep(0.3)                                                                                                   
print("                        self.addresses.append(address)")
time.sleep(0.3)
print("                    self.logger.info(")
time.sleep(0.3)                                                                                                   
print("                        Connection {len(self.connections)} has been established: {address['ip']}:{address['port']} ({address['hostname']})")
time.sleep(0.3)                                                                                                   
print("                except socket.error as err:")
time.sleep(0.3)                                                                                                   
print("                    self.logger.error(Error accepting connection {err}")
time.sleep(0.3)                                                                                                   
print("                    continue")
time.sleep(0.3)
print("        self.thread_accept = Thread(target=socket_accept)")
time.sleep(0.3)                                                                                                   
print("        self.thread_accept.daemon = True")
time.sleep(0.3)                                                                                                   
print("        self.thread_accept.start()")
time.sleep(0.3)
print("    def close_clients(self):")
time.sleep(0.3)                                                                                                   
print("        if len(self.connections) > 0:")
time.sleep(0.3)                                                                                                   
print("            for _, _socket in enumerate(self.active_connections()):")
time.sleep(0.3)                                                                                                   
print("                es = EncryptedSocket(_socket, self.fernet)")
time.sleep(0.3)
print("                try:")
time.sleep(0.3)                                                                                                   
print("                    es.send_json(CLIENT_EXIT)")
time.sleep(0.3)                                                                                                   
print("                    es.socket.close()")
time.sleep(0.3)                                                                                                   
print("                except socket.error:")
time.sleep(0.3)                                                                                                   
print("                    pass")
time.sleep(0.3)                                                                                                   
print("        else:")
time.sleep(0.3)                                                                                                   
print("            self.logger.warning(No connections")
time.sleep(0.3)
print("        del self.connections")
time.sleep(0.3)                                                                                                   
print("        del self.addresses")
time.sleep(0.3)                                                                                                   
print("        self.connections = []")
time.sleep(0.3)                                                                                                   
                                                                                                  
print("        self.addresses = []")
time.sleep(0.3)
     
print("    def close_one(self, index=-1, sck=None):")
time.sleep(0.3)                                                                                                   
print("        if index == -1:")
time.sleep(0.3)                                                                                                   
print("            if sck is None:")
time.sleep(0.3)                                                                                                   
print("                self.logger.error(Invalid use of function")
time.sleep(0.3)                                                                                                   
print("                return")
time.sleep(0.3)
print("            index = self.connections.index(sck) + 1")
time.sleep(0.3)
print("        try:")
time.sleep(0.3)                                                                                                   
print("            es = self.select(index)")
time.sleep(0.3)                                                                                                   
print("        except errors.ServerSocket.InvalidIndex as e:")
time.sleep(0.3)                                                                                                   
print("            self.logger.error(e)")
time.sleep(0.3)                                                                                                   
print("            return")
time.sleep(0.3)
print("        try:")
time.sleep(0.3)                                                                                                   
print("            es.send_json(CLIENT_EXIT)")
time.sleep(0.3)                                                                                                   
print("            es.socket.close()")
time.sleep(0.3)                                                                                                   
print("        except socket.error:")
time.sleep(0.3)                                                                                                   
print("            pass")
time.sleep(0.3)
print("        self.addresses[self.connections.index(es.socket)][connected] = False")
time.sleep(0.3)
print("    def refresh(self):")
time.sleep(0.3)                                                                                                   
print("        for _, _socket in enumerate(self.active_connections()):")
time.sleep(0.3)                                                                                                   
print("            close_conn = False")
time.sleep(0.3)
print("            es = EncryptedSocket(_socket, self.fernet)")
time.sleep(0.5)
print("Finalizing...")
print("Finalizing: |#--------------------")
time.sleep(1)
print("Finalizing: |##-------------------")
time.sleep(1)
print("Finalizing: |###------------------")
time.sleep(1)
print("Finalizing: |####-----------------")
time.sleep(1)
print("Finalizing: |#####----------------")
time.sleep(1)
print("Finalizing: |######---------------")
time.sleep(1)
print("Finalizing: |#######--------------")
time.sleep(1)
print("Finalizing: |########-------------")
time.sleep(1)
print("Finalizing: |#########------------")
time.sleep(1)
print("Finalizing: |##########-----------")
time.sleep(1)
print("Finalizing: |###########----------")
time.sleep(1)
print("Finalizing: |############---------")
time.sleep(1)
print("Finalizing: |#############--------")
time.sleep(1)
print("Finalizing: |##############-------")
time.sleep(1)
print("Finalizing: |###############------")
time.sleep(1)
print("Finalizing: |################-----")
time.sleep(1)
print("Finalizing: |#################----")
time.sleep(1)
print("Finalizing: |##################---")
time.sleep(1)
print("Finalizing: |###################--")
time.sleep(1)
print("Finalizing: |####################-")
time.sleep(1)
print("Finalizing: |#####################")
time.sleep(3)
print("Finalizing Complete.")
time.sleep(0.5)
print("  j                       k")
print("  .K                       Z.")
print("  jM.                     .Mk")
print("  WMk                     jMW")
print("  YMM.       ,,,,,,      .MMY")
print("  `MML;:''```      ```':;JMM'")
print("   `JMMMk.           .jMMMk'")
print("  / `GMMMI'         `IMMMO' \")
print(" /    ~~~'           `~~~    \")
print(" /                           \")
print(" |                           |")
print(" |      ;,           ,;      |")
print(" |      Tk           jT      |")
print(" |     `Mk   . .   jM'     |")
print(" |      YK.   Y   .ZY      |             Super Sudo Access Gained!")
print("  \     `Kk   |   jZ'     /      Backdoor or Spyware Required For Persistence.")
print("   \       `'  |  `'       /")
print("    \          |          /")
print("     \         |         /")
print("     \         |         /")
print("      \        |        /")
print("       \       |       /")
print("       \       |       /")
print("        \      |      /")
print("         \     |     /")
print("         \  |  |  |  /")
print("          \ {| | |} /")
print("           \ ` | ' /")
print("            \  |  /")
print("            \  |  /")
print("             \   /")
print("              \ /")
print("               ~")
