#python
import os
import sys
import time
import random
#--------------
print("⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⢠⡆⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠈⣷⣄⠀⠀⠀⠀⣾⣷⠀⠀⠀⠀⣠⣾⠃⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⢿⠿⠃⠀⠀⠀⠉⠉⠁⠀⠀⠐⠿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣤⣶⣶⣶⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⢀⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⣠⣶⣿⣿⡿⣿⣿⣿⡿⠋⠉⠀⠀⠉⠙⢿⣿⣿⡿⣿⣿⣷⣦⡀⠀⠀⠀")
print("⠀⢀⣼⣿⣿⠟⠁⢠⣿⣿⠏⠀⠀⢠⣤⣤⡀⠀⠀⢻⣿⣿⡀⠙⢿⣿⣿⣦⠀⠀         All")
print("⣰⣿⣿⡟⠁⠀⠀⢸⣿⣿⠀⠀⠀⢿⣿⣿⡟⠀⠀⠈⣿⣿⡇⠀⠀⠙⣿⣿⣷⡄         Seeing")
print("⠈⠻⣿⣿⣦⣄⠀⠸⣿⣿⣆⠀⠀⠀⠉⠉⠀⠀⠀⣸⣿⣿⠃⢀⣤⣾⣿⣿⠟⠁         Eye.")
print("⠀⠀⠈⠻⣿⣿⣿⣶⣿⣿⣿⣦⣄⠀⠀⠀⢀⣠⣾⣿⣿⣿⣾⣿⣿⡿⠋⠁⠀⠀")
print("⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠁⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠛⠿⠿⠿⠿⠿⠿⠛⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⢰⣷⡦⠀⠀⠀⢀⣀⣀⠀⠀⠀⢴⣾⡇⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⣸⠟⠁⠀⠀⠀⠘⣿⡇⠀⠀⠀⠀⠙⢷⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠻⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀")
time.sleep(2)
print("██████╗ ██╗  ██╗ ██████╗  ██████╗ ███╗   ███╗ █████╗ ")
print("██╔══██╗██║  ██║██╔═══██╗██╔═══██╗████╗ ████║██╔══██╗")
print("██████╔╝███████║██║   ██║██║   ██║██╔████╔██║███████║")
print("██╔═══╝ ██╔══██║██║   ██║██║   ██║██║╚██╔╝██║██╔══██║")
print("██║     ██║  ██║╚██████╔╝╚██████╔╝██║ ╚═╝ ██║██║  ██║")
print("╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝")
time.sleep(2)
print("In Your System Since 2020.")
time.sleep("1")
print("Scanning Main Network for Open Port or Gateway...")
print("Scanning: |#--------------------")
time.sleep(0.5)
print("Scanning: |##-------------------")
time.sleep(0.5)
print("Scanning: |###------------------")
time.sleep(0.5)
print("Scanning: |####-----------------")
time.sleep(0.5)
print("Scanning: |#####----------------")
time.sleep(0.5)
print("Scanning: |######---------------")
time.sleep(0.5)
print("Scanning: |#######--------------")
time.sleep(0.5)
print("Scanning: |########-------------")
time.sleep(0.5)
print("Scanning: |#########------------")
time.sleep(0.5)
print("Scanning: |##########-----------")
time.sleep(0.5)
print("Scanning: |###########----------")
time.sleep(0.5)
print("Scanning: |############---------")
time.sleep(0.5)
print("Scanning: |#############--------")
time.sleep(0.5)
print("Scanning: |##############-------")
time.sleep(0.5)
print("Scanning: |###############------")
time.sleep(0.5)
print("Scanning: |################-----")
time.sleep(0.5)
print("Scanning: |#################----")
time.sleep(0.5)
print("Scanning: |##################---")
time.sleep(0.5)
print("Scanning: |###################--")
time.sleep(0.5)
print("Scanning: |####################-")
time.sleep(0.5)
print("Scanning: |#####################")
print("def main():")
time.sleep(0.6)      
print("	parser,args = PArguments.Main_Arguments()")
time.sleep(0.6)
print("      if args.target == False:")
time.sleep(0.6)
print("      if args.help == False:")
time.sleep(0.6)
print("     sys.exit(UsageMain())")
time.sleep(0.6) 
print("      else:")
time.sleep(0.6)
print("			sys.exit(parser.print_help())")
time.sleep(0.6)
print("      else:")
time.sleep(0.6)
print("      process = getProcess(args)")
time.sleep(0.6)
print("      if len(process()) == 0:")
time.sleep(0.6)
print("      if args.help == False:")
time.sleep(0.6)
print("      sys.exit(UsageMain())")
time.sleep(0.6)
print("      else:")
time.sleep(0.6)
print("      sys.exit(parser.print_help())")
time.sleep(0.6)
print("      else:")
time.sleep(0.6)
print("      for _ in process():")
time.sleep(0.6)
print("				Handle(_,args)")
time.sleep(0.6)

print("      if __name__ == '__main__':")
time.sleep(0.6)
print("      main()")
time.sleep(0.6)
print("      class Ping:")
time.sleep(0.6)
print("      def __init__(self,tgt,to):")
time.sleep(0.6)
print("      self.tgt = domain_resolver(tgt,True)")
time.sleep(0.6)
print("      self.to = to")
time.sleep(0.6)
print("      self.id = os.getpid() & 0xFFFF")
time.sleep(0.6)
print("      self.my_socket = create_icmp_socket(self.to)")
time.sleep(0.6)
print("      builder = PingHeader(self.tgt)")
time.sleep(0.6)
print("		self.pkt = builder.building_packet()")
time.sleep(0.6)
print("      def send(self):")
time.sleep(0.6)
print("      send_time = time.time()")
time.sleep(0.6)
print("      self.my_socket.sendto(self.pkt, (self.tgt, 1))")
time.sleep(0.6)
print("		return send_time")
time.sleep(0.6)
print("      def receive(self):")
time.sleep(0.6)
print("      while True:")
time.sleep(0.6)
print("      select_start = time.time()")
time.sleep(0.6)
print("     inputready, outputready, exceptready = select.select([self.my_socket], [], [], self.to)")
time.sleep(0.6) 
print("      select_duration = (time.time() - select_start)")
time.sleep(0.6)
print("      if inputready == []:")
time.sleep(0.6)
print("				return 0, 0, 0, None, None")
time.sleep(0.6)
print("			packet, address = self.my_socket.recvfrom(65536)")
time.sleep(0.6)
print("			receive_time = time.time()")
time.sleep(0.6)
print("      icmpHeader = packet[20:28]")
time.sleep(0.6)
print("      type, code, checksum, packetID, sequence = struct.unpack(bbHHh, icmpHeader)")
time.sleep(0.6)
print("      if packetID == self.id:")
time.sleep(0.6)
print("				return receive_time")
time.sleep(0.6)
print("			timeout = timeout - select_duration")
time.sleep(0.6)
print("      if timeout <= 0:")
time.sleep(0.6)
print("				return 0, 0, 0, None, None")
time.sleep(0.6)
print("	def _start_icmp(self):")
time.sleep(0.6)		
print("      for i in range(0,1):")
time.sleep(0.6)
print("      try:")
time.sleep(0.6)
print("      send_time = self.send()")
time.sleep(0.6)
print("      receive_time = self.receive()")
time.sleep(0.6)
print("      except:")
time.sleep(0.6)
print("				return None")
time.sleep(0.6)
print("		return (receive_time - send_time) * 10")
time.sleep(0.5)
print("Scan Complete")
print("Exploitable Open Port:")
time.sleep(1)
print(random.randint(45, 65535))
time.sleep(1)
question = input('Execute?: ')
if question == 'y' or 'Y'
print("class Server:")
print("    def __init__(self, port):")
print("        self.logger = logging.getLogger(LOGGER_ID)")

print("        self.thread_accept = None")
print("        self.port = port")
print("        self.connections = []")
print("        self.addresses = []")

 print("       self.encryption = Encryption()")
 print("       self.fernet = self.encryption.fernet")

 print("       self.listener = socket.socket()")

print("        try:")
print("            self.listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR,")
print("                                     1)")
print("        except socket.error as e:")
print("            self.logger.error(Error creating socket {e}")
print("            sys.exit(0)")

print("    def listen_asych(self):")
print("        def bind():")
print("            try:")
print("                self.listener.bind(("0.0.0.0", self.port))")
print("                self.listener.listen(20)")
print("            except socket.error as e:")
print("                self.logger.warning(Error binding socket {e}\nRetrying...)")
print("                time.sleep(3)")
print("                bind()")

print("        bind()")

print("        self.logger.info(fListening on port {self.port}")")

print("        def socket_accept():")
print("            while True:")
print("                try:")
print("                    _socket, address = self.listener.accept()")
print("                    _socket.setblocking(True)")

print("                    es = EncryptedSocket(_socket, self.fernet)")

                    
                    
print("                    es.send(base64.b64encode(self.encryption.key), False)")
print("                    self.logger.debug(send key: {self.encryption.key}")")

print("                    while True:")
                        
print("                        response = es.recv_json()")
print("                        if response[key] == CLIENT_HANDSHAKE:")
print("                            break")

print("                    address = {**{ip: address[0], port: address[1]}, **response[value"], **{"connected: True}}")

print("                    if es.socket in self.connections:")
print("                        self.addresses[self.connections.index(es.socket)][connected] = True")
print("                    else:")
print("                        self.connections.append(es.socket)")
print("                        self.addresses.append(address)")

print("                    self.logger.info(")
print("                        Connection {len(self.connections)} has been established: {address['ip']}:{address['port']} ({address['hostname']})")")
print("                except socket.error as err:")
print("                    self.logger.error(Error accepting connection {err}")")
print("                    continue")

print("        self.thread_accept = Thread(target=socket_accept)")
print("        self.thread_accept.daemon = True")
print("        self.thread_accept.start()")

print("    def close_clients(self):")
print("        if len(self.connections) > 0:")
print("            for _, _socket in enumerate(self.active_connections()):")
print("                es = EncryptedSocket(_socket, self.fernet)")

print("                try:")
print("                    es.send_json(CLIENT_EXIT)")
print("                    es.socket.close()")
print("                except socket.error:")
print("                    pass")
print("        else:")
print("            self.logger.warning(No connections")")

print("        del self.connections")
print("        del self.addresses")
print("        self.connections = []")
print("        self.addresses = []")

     
print("    def close_one(self, index=-1, sck=None):")
print("        if index == -1:")
print("            if sck is None:")
print("                self.logger.error(Invalid use of function")")
print("                return")

print("            index = self.connections.index(sck) + 1")

print("        try:")
print("            es = self.select(index)")
print("        except errors.ServerSocket.InvalidIndex as e:")
print("            self.logger.error(e)")
print("            return")

print("        try:")
print("            es.send_json(CLIENT_EXIT)")
print("            es.socket.close()")
print("        except socket.error:")
print("            pass")

print("        self.addresses[self.connections.index(es.socket)][connected] = False")

print("    def refresh(self):")
print("        for _, _socket in enumerate(self.active_connections()):")
print("            close_conn = False")

print("            es = EncryptedSocket(_socket, self.fernet)")
time.sleep(0.5)
print("Finalizing...")
print("Finalizing: |#--------------------")
time.sleep(1)
print("Finalizing: |##-------------------")
time.sleep(1)
print("Finalizing: |###------------------")
time.sleep(1)
print("Finalizing: |####-----------------")
time.sleep(1)
print("Finalizing: |#####----------------")
time.sleep(1)
print("Finalizing: |######-----------
time.sleep(1)
print("Finalizing: |#######--------------")
time.sleep(1)
print("Finalizing: |########-------------")
time.sleep(1)
print("Finalizing: |#########------------")
time.sleep(1)
print("Finalizing: |##########-----------")
time.sleep(1)
print("Finalizing: |###########----------")
time.sleep(1)
print("Finalizing: |############---------")
time.sleep(1)
print("Finalizing: |#############--------")
time.sleep(1)
print("Finalizing: |##############-------")
time.sleep(1)
print("Finalizing: |###############------")
time.sleep(1)
print("Finalizing: |################-----")
time.sleep(1)
print("Finalizing: |#################----")
time.sleep(1)
print("Finalizing: |##################---")
time.sleep(1)
print("Finalizing: |###################--")
time.sleep(1)
print("Finalizing: |####################-")
time.sleep(1)
print("Finalizing: |#####################")
time.sleep(3)
print("Finalizing Complete.")
time.sleep(0.5)
print("          j                       k")
print("          .K                       Z.")
print("          jM.                     .Mk")
print("          WMk                     jMW")
print("          YMM.       ,,,,,,      .MMY")
print("          `MML;:''```      ```':;JMM'")
print("          /`JMMMk.           .jMMMk'\")
print("          / `GMMMI'         `IMMMO' \")
print("         /    ~~~'           `~~~    \")
print("         /                           \")
print("         |                           |")
print("         |      ;,           ,;      |")
print("         |      Tk           jT      |")
print("         |     `Mk   . .   jM'     |")
print("          |      YK.   Y   .ZY      |             Super Sudo Access Gained!")
print("          \     `Kk   |   jZ'     /      Backdoor or Spyware Required For Persistence.")
print("           \       `'  |  `'       /")
print("            \          |          /")
print("             \         |         /")
print("             \         |         /")
print("              \        |        /")
print("               \       |       /")
print("               \       |       /")
print("                \      |      /")
print("                 \     |     /")
print("                 \  |  |  |  /")
print("                  \ {| | |} /")
print("                   \ ` | ' /")
print("                    \  |  /")
print("                    \  |  /")
print("                     \   /")
print("                      \ /")
print("                       ~")
