#python
import os
import sys
import time
import random
#--------------
print("⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⢠⡆⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠈⣷⣄⠀⠀⠀⠀⣾⣷⠀⠀⠀⠀⣠⣾⠃⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⢿⠿⠃⠀⠀⠀⠉⠉⠁⠀⠀⠐⠿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣤⣶⣶⣶⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⢀⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⣠⣶⣿⣿⡿⣿⣿⣿⡿⠋⠉⠀⠀⠉⠙⢿⣿⣿⡿⣿⣿⣷⣦⡀⠀⠀⠀")
print("⠀⢀⣼⣿⣿⠟⠁⢠⣿⣿⠏⠀⠀⢠⣤⣤⡀⠀⠀⢻⣿⣿⡀⠙⢿⣿⣿⣦⠀⠀         All")
print("⣰⣿⣿⡟⠁⠀⠀⢸⣿⣿⠀⠀⠀⢿⣿⣿⡟⠀⠀⠈⣿⣿⡇⠀⠀⠙⣿⣿⣷⡄         Seeing")
print("⠈⠻⣿⣿⣦⣄⠀⠸⣿⣿⣆⠀⠀⠀⠉⠉⠀⠀⠀⣸⣿⣿⠃⢀⣤⣾⣿⣿⠟⠁         Eye.")
print("⠀⠀⠈⠻⣿⣿⣿⣶⣿⣿⣿⣦⣄⠀⠀⠀⢀⣠⣾⣿⣿⣿⣾⣿⣿⡿⠋⠁⠀⠀")
print("⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠁⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠛⠿⠿⠿⠿⠿⠿⠛⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⢰⣷⡦⠀⠀⠀⢀⣀⣀⠀⠀⠀⢴⣾⡇⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⣸⠟⠁⠀⠀⠀⠘⣿⡇⠀⠀⠀⠀⠙⢷⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠻⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀")
time.sleep(2)
print("██████╗ ██╗  ██╗ ██████╗  ██████╗ ███╗   ███╗ █████╗ ")
print("██╔══██╗██║  ██║██╔═══██╗██╔═══██╗████╗ ████║██╔══██╗")
print("██████╔╝███████║██║   ██║██║   ██║██╔████╔██║███████║")
print("██╔═══╝ ██╔══██║██║   ██║██║   ██║██║╚██╔╝██║██╔══██║")
print("██║     ██║  ██║╚██████╔╝╚██████╔╝██║ ╚═╝ ██║██║  ██║")
print("╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝")
time.sleep(2)
print("In Your System Since 2020.")
time.sleep("1")
print("Scanning Main Network for Open Port or Gateway...")
print("Scanning: |#--------------------")
time.sleep(0.5)
print("Scanning: |##-------------------")
time.sleep(0.5)
print("Scanning: |###------------------")
time.sleep(0.5)
print("Scanning: |####-----------------")
time.sleep(0.5)
print("Scanning: |#####----------------")
time.sleep(0.5)
print("Scanning: |######---------------")
time.sleep(0.5)
print("Scanning: |#######--------------")
time.sleep(0.5)
print("Scanning: |########-------------")
time.sleep(0.5)
print("Scanning: |#########------------")
time.sleep(0.5)
print("Scanning: |##########-----------")
time.sleep(0.5)
print("Scanning: |###########----------")
time.sleep(0.5)
print("Scanning: |############---------")
time.sleep(0.5)
print("Scanning: |#############--------")
time.sleep(0.5)
print("Scanning: |##############-------")
time.sleep(0.5)
print("Scanning: |###############------")
time.sleep(0.5)
print("Scanning: |################-----")
time.sleep(0.5)
print("Scanning: |#################----")
time.sleep(0.5)
print("Scanning: |##################---")
time.sleep(0.5)
print("Scanning: |###################--")
time.sleep(0.5)
print("Scanning: |####################-")
time.sleep(0.5)
print("Scanning: |#####################")
time.sleep(0.5)
print("Scan Complete")
print("Exploitable Open Port:")
time.sleep(1)
print(random.randint(45, 65535))
time.sleep(1)
