#Python
import time
import os
import sys
import random
#-------------
time.sleep(2)
print("         .AMMMMMMMMMMA.")
print("       .AV. :::.:.:.::MA.")
print("      A' :..        : .:`A")
print("     A'..              . `A.")
print("    A' :.    :::::::::  : :`A")
print("    M  .    :::.:.:.:::  . .M")
print("    M  :   ::.:.....::.:   .M")
print("    V : :.::.:........:.:  :V")
print("   A  A:    ..:...:...:.   A A")
print("  .V  MA:.....:M.::.::. .:AM.M")
print(" A'  .VMMMMMMMMM:.:AMMMMMMMV: A")
print(":M .  .`VMMMMMMV.:A `VMMMMV .:M:")
print(" V.:.  ..`VMMMV.:AM..`VMV' .: V")
print("  V.  .:. .....:AMMA. . .:. .V")
print("   VMM...: ...:.MMMM.: .: MMV")
print("       `VM: . ..M.:M..:::M'")
print("         `M::. .:.... .::M")
print("          M:.  :. .... ..M")
print("          V:  M:. M. :M .V")
print("          `V.:M.. M. :M.V'")
print("Best to leave a nice little way inside a network, make yourself at home!")
print("   ▄▄▄▄▄ ▀▄    ▄  ▄▄▄▄▄   ██▄   ████▄ ████▄ █▄▄▄▄ ")
print("  █     ▀▄ █  █  █     ▀▄ █  █  █   █ █   █ █  ▄▀ ")
print("▄  ▀▀▀▀▄    ▀█ ▄  ▀▀▀▀▄   █   █ █   █ █   █ █▀▀▌  ")
print(" ▀▄▄▄▄▀     █   ▀▄▄▄▄▀    █  █  ▀████ ▀████ █  █  ")
print("          ▄▀              ███▀                █   ")
sleep.time(3)
print("Scanning Main Network for Open Port or Gateway...")
print("Scanning: |#--------------------")
time.sleep(0.5)
print("Scanning: |##-------------------")
time.sleep(0.5)
print("Scanning: |###------------------")
time.sleep(0.5)
print("Scanning: |####-----------------")
time.sleep(0.5)
print("Scanning: |#####----------------")
time.sleep(0.5)
print("Scanning: |######---------------")
time.sleep(0.5)
print("Scanning: |#######--------------")
time.sleep(0.5)
print("Scanning: |########-------------")
time.sleep(0.5)
print("Scanning: |#########------------")
time.sleep(0.5)
print("Scanning: |##########-----------")
time.sleep(0.5)
print("Scanning: |###########----------")
time.sleep(0.5)
print("Scanning: |############---------")
time.sleep(0.5)
print("Scanning: |#############--------")
time.sleep(0.5)
print("Scanning: |##############-------")
time.sleep(0.5)
print("Scanning: |###############------")
time.sleep(0.5)
print("Scanning: |################-----")
time.sleep(0.5)
print("Scanning: |#################----")
time.sleep(0.5)
print("Scanning: |##################---")
time.sleep(0.5)
print("Scanning: |###################--")
time.sleep(0.5)
print("Scanning: |####################-")
time.sleep(0.5)
print("Scanning: |#####################")
time.sleep(0.5)
print("Scan Complete")
print("Exploitable Open Port:")
time.sleep(1)
print(random.randint(45, 65535))
sleep.time(1)
question = input('Upload Backdoor?: ')
if question == 'y' or 'Y':
print("Uploading Backdoor to Main Network...")
time.sleep(3)
print("Uploading: |#--------------------")
time.sleep(0.5)
print("Uploading: |##-------------------")
time.sleep(0.5)
print("Uploading: |###------------------")
time.sleep(0.5)
print("Uploading: |####-----------------")
time.sleep(0.5)
print("Uploading: |#####----------------")
time.sleep(0.5)
print("Uploading: |######---------------")
time.sleep(0.5)
print("Uploading: |#######--------------")
time.sleep(0.5)
print("Uploading: |########-------------")
time.sleep(0.5)
print("Uploading: |#########------------")
time.sleep(0.5)
print("Uploading: |##########-----------")
time.sleep(0.5)
print("Uploading: |###########----------")
time.sleep(0.5)
print("Uploading: |############---------")
time.sleep(0.5)
print("Uploading: |#############--------")
time.sleep(0.5)
print("Uploading: |##############-------")
time.sleep(0.5)
print("Uploading: |###############------")
time.sleep(0.5)
print("Uploading: |################-----")
time.sleep(0.5)
print("Uploading: |#################----")
time.sleep(0.5)
print("Uploading: |##################---")
time.sleep(0.5)
print("Uploading: |###################--")
time.sleep(0.5)
print("Uploading: |####################-")
time.sleep(0.5)
print("Uploading: |#####################")
time.sleep(0.5)
print("Upload Complete")
